#! /usr/bin/env python3
import sys
import subprocess
import shutil

tests = (('r2h', ['covtest', 'test/unittests/test_r2h.py', 'rst2html.py']),               
         ('rhfn', ['covtest', 'test/unittests/test_rhfn.py', 'rst2html_functions.py']),   
         ('rhdir', ['covtest', 'test/unittests/test_rhdir.py', 'rst2html_directives.py']),  
         ('dmlf', ['covtest', 'test/unittests/test_dmlf.py', 'docs2fs.py']),	          
         ('dmlm', ['covtest', 'test/unittests/test_dmlm.py', 'docs2mongo.py']),	          
         ('dmlp', ['covtest', 'test/unittests/test_dmlp.py', 'docs2pg.py']))	          
usage = 'usage: ./unittests [ARG] - where arg is a value from {}'.format(tests)

do = ''
if len(sys.argv) == 2:
    do = sys.argv[1]
elif len(sys.argv) == 1:
    do = 'all'
ok = False
for test, command in tests:
    if do == test or do == 'all':
        ok = True
        subprocess.run(command)
if not ok:
    print(usage)
