# rename this file to settings.yml to make it work
# note that alternative setting files can be defined as settings_<sitename>.yml
# also note that settings files can (or should) be edited from inside the application

# this file defines the following items:

# mirror   - a unique name for this particular site
mirror: magiokis_vv

# mirror_url   - http address of the mirror environment on your local machine
url: http://preview.magiokis.nl

# css           - a list of locations of css files (should be absolute urls, so starting with http(s): )
# these are used in the rst to html conversion, so should be resolvable
css:
- http://preview.magiokis.nl/css/reset.css
- http://www.magiokis.nl/css/magiokis.css

# wid, hig - width and height of text area in the web interface
wid: 100
hig: 32
# lang      - language to be used in the web interface elements (not the contents!)
# currently en(glish) and nl (dutch) are available
lang: en

# starthead - text lines to copy directly after the <head> element (to be executed first)
# endhead  - text lines to copy directly before the </head> element (to be executed last)
# these should be valid HTML
starthead:

endhead:

# these can't be defined using directives because the code these generate goes into the
# document body
